exclude: _vendor
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args: ["-i", "--remove-all-unused-imports"]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  # official flake8 doesn't support pyproject.toml configuration.
  - repo: https://github.com/csachs/pyproject-flake8
    rev: 10ce82f40319e62c3e0db7f25106d9823df347ef
    hooks:
      - id: pyproject-flake8
        name: pyproject-flake8
